apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZTFxMDg5NForaWt3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBM01EVXhOak00TVRKYUZ3MHpOakEzTURJeE5qUXpNVEphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURIenIyekJTWmtTVjdxNzZ0N1NIOG1TZ09wQkw4cU5ybnJTLy8rUEQzMkQ3ZkV0WjJxZ0J6SUhWWEUKZFBWVndCNks5Y2NUZDFZQm0rOVovcXg5UzFLVGVqc0NvUjBQWHRmMFE0OVBxWWU3eE1SRHJmVTB3VGhkRGgveApudVA1K0ROZG9TL2hMY1VMdTBoZXRiZllVTTZiZklrRGZ1N056b3E3dGZUYU1vTjh6eDF4dWhrNTFJbFRrb2J3CmcwaUdscHdKL3hKREx6QUtCYkMwdW9NUGdoVlEvRDhVRHBmaExGKzZBeEVVMGF0QkYySEx0REI0SERHU09yQkQKL3NZektRTnIvQ2FhWU5IaVNEeEZUUlcwZVZmUXZ0ZmRiSC80NmZRTEo3aVRsajNFWnBjaFNRdnpVK3NuSVNGZAo1b2J5a2pYSXBUdkhBU3FGTFowSHlibGFSaFFEQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSTzE2N3lZTVB1T2JXT3I2QjhVODUyL3ltT1lUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkhDMGF5c0ZSYgoxeFZBVjVSalVWM0xEa202TDFmRWVzTlNaNmtaYWpnZGJ6bHd0Tnhad0ZOVmhGOE9idzFxSXVCSnR0b0lHaDRDCkV5UEFScFYrU2s4aE5DWmJuM0lwQmRsd1FRQTE2WVlEMUNvTEFqVlRaY25VcnVXS3U5V1o5U1hCcHB5WFk1M2oKT3p1Rk1hNWZIS0xaOVVMeStHM1o0cVpzVzBrNFkyYUYrc29sSVYwcTVnYytvYUVkL1RIWjExcUd3KzYwdzk1TgpPZ3k0cnpDOHBlUXZLY3ZhMFhSc0lES2JEWGRFbWlZei9LOFdYSDVsRlhnSVk0U1NsdWR2LzF2RFRUbGNINnZCCllkNjVocWlKN0R5MlR2c3V1cTNxbklPT045R1pwQUFJalNMRzB6b1AwWWloNEkyMjlDZ09qYjJ3YXdQNjdEUUgKMVRyUmFrZnVsT0w3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://D933792D0C34E6E2AA6CF4DFB0DB938E.gr7.eu-north-1.eks.amazonaws.com
  name: aws-managed-cluster.eu-north-1.eksctl.io
contexts:
- context:
    cluster: aws-managed-cluster.eu-north-1.eksctl.io
    user: admin@aws-managed-cluster.eu-north-1.eksctl.io
  name: admin@aws-managed-cluster.eu-north-1.eksctl.io
current-context: admin@aws-managed-cluster.eu-north-1.eksctl.io
kind: Config
users:
- name: admin@aws-managed-cluster.eu-north-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - eks
      - get-token
      - --output
      - json
      - --cluster-name
      - aws-managed-cluster
      - --region
      - eu-north-1
      command: aws
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      provideClusterInfo: false
