#!/usr/bin/env

@Library('Jenkins-shared-library')

def APP_PATH = "aws-exercises/app"

pipeline {
    agent any
    tools {
        nodejs 'node'
    }
    stages {
        stage('Check commit message') {
            steps {
                script {
                    commitCheck()
                }
            }
        }
        stage('Increment app version') {
            steps {
                script {
                    incrementAppVersion(APP_PATH)
                }
            }
        }
        stage('Test code') {
            steps {
                script {
                    echo 'Running test'
                    sh "cd ${APP_PATH} && npm install && npm run test"
                    echo "Executing pipeline for branch $BRANCH_NAME "
                }
            }
        }
        stage('Build docker image') {
            when {
                expression {
                    BRANCH_NAME == "master"
                }
            }
            steps {
                script {
                    buildDockerImage(
                        "lihanda/demo-app:${IMAGE_NAME}",
                        APP_PATH
                    )
                }
            }
        }
        stage('Deploy') {
            when {
                expression {
                    BRANCH_NAME == "master"
                }
            }
            steps {
                script {
                    echo 'Deploying the application to EC2 instance..'

                    def shellCmd = "bash ./server-cmds.sh ${IMAGE_NAME}"

                    def ec2Instance = "ec2-user@13.53.125.162"

                    sshagent(['ec2-server-key']) {
                        sh "scp -o StrictHostKeyChecking=no ${APP_PATH}/server-cmds.sh ${ec2Instance}:/home/ec2-user"
                        sh "scp -o StrictHostKeyChecking=no ${APP_PATH}/docker-compose.yaml ${ec2Instance}:/home/ec2-user"
                        sh "ssh -o StrictHostKeyChecking=no ${ec2Instance} ${shellCmd}"
                    }
                }
            }
        }
        stage('Commit version update') {
            steps {
                script {
                    commitVersionUpdate()
                }
            }
        }
    }

}
