services:
  java-maven-app:
    image: 'lihanda/demo-app:java-maven-1.0'
    ports:
      - 8081:8080
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my-pwd

