#!/usr/bin/env groovy

library identifier: 'jenkins-shared-library@main', retriever: modernSCM(
    [$class: 'GitSCMSource',
    remote: 'https://gitlab.com/lihandafabius/jenkins-shared-library.git',
    credentialsID: 'gitlab-credentials'
    ]
)

pipeline {
    agent any
    tools {
        maven 'maven-9'
    }
    environment {
        IMAGE_NAME = 'lihanda/demo-app:java-maven-1.0'
    }
    stages {
        stage('build app') {
            steps {
                echo 'building application jar...'
                buildJar()
            }
        }
        stage('build image') {
            steps {
                script {
                    echo 'building the docker image...'
                    buildImage(env.IMAGE_NAME)
                    dockerLogin()
                    dockerPush(env.IMAGE_NAME)
                }
            }
        }
        stage("deploy") {
            steps {
                script {
                    echo 'deploying docker image to EC2...'
                    def dockerComposeCmd = "docker compose -f docker-compose.yaml up --detach"
                    sshagent(['ec2-server-key']) {
                        sh 'scp aws/java-maven-app/docker-compose.yaml ubuntu@16.16.92.173:/home/ubuntu'
                        sh "ssh -o StrictHostKeyChecking=no ubuntu@16.16.92.173 ${dockerComposeCmd}"
                    }
                }
            }
        }
    }
}
