apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysql-java-app-ingress
  namespace: java-app
spec:
  ingressClassName: nginx
  rules:
  - host: "aa9addd5f67794b09ad020e52fbe1927-377062853.eu-north-1.elb.amazonaws.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: java-mysql-app-service
            port:
              number: 8080
