apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: java-app
type: Opaque
data:
  DB_USER: bXl1c2Vy
  DB_PWD: bXlwYXNzd29yZA==
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=
  MYSQL_DATABASE: YXBwZGI=