apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: mysql-java-app-ingress
spec:
  ingressClassName: nginx
  rules:
   - host: a000a5612ce834dabb24180356c27f12-1253371355.eu-north-1.elb.amazonaws.com
     http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: java-mysql-app-service
              port:
                number: 8080