apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: monitoring
spec:
  route:
    receiver: 'email'
    repeatInterval: 30m  # if the issue still persist send another email in 30 mins time
    routes:
    - matchers:
      - name: alertname
        value: HostHighCpuLoad
    - matchers:
      - name: alertname
        value: KubernetesPodCrashLooping
      repeatInterval: 10m

  receivers:
  - name: 'email'
    emailConfigs:
    - to: 'fabiuslihandaachevi@gmail.com'
      from: 'fabiuslihandaachevi@gmail.com'
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'fabiuslihandaachevi@gmail.com'
      authIdentity: 'fabiuslihandaachevi@gmail.com'
      authPassword:
        name: gmail-auth
        key: password
