apiVersion: monitoring.coreos.com/v1beta1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: monitoring
spec:
  receivers:
  - name: 'email'
    emailConfigs:
    - to: 'fabiuslihandaachevi@gmail.com'
      from: 'fabiuslihandaachevi@gmail.com'
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'fabiuslihandaachevi@gmail.com'
      authIdentity: 'fabiuslihandaachevi@gmail.com'
      authPassword:
        name: gmail-auth
        key: password
