#!/usr/bin/env


pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }


        stage('Fetch ECR Images') {
            steps {
                script {
                    dir('automation_with_python_exercises') {

                        withCredentials([
                            string(
                                credentialsId: 'jenkins_aws_access_key_id',
                                variable: 'AWS_ACCESS_KEY_ID'
                            ),
                            string(
                                credentialsId: 'jenkins_aws_secret_access_key',
                                variable: 'AWS_SECRET_ACCESS_KEY'
                            )
                        ]) {

                            def images = sh(
                                script: '''
                                    /opt/jenkins-venv/bin/python fetch_images.py
                                ''',
                                returnStdout: true
                            ).trim()

                            echo "Available images:"
                            echo images

                            env.IMAGE_LIST = images
                        }
                    }
                }
            }
        }

        stage('Select Image') {
            steps {
                script {
                    def selectedImage = input(
                        message: 'Select the image to deploy:',
                        ok: 'Continue',
                        parameters: [
                            choice(
                                name: 'IMAGE',
                                choices: env.IMAGE_LIST,
                                description: 'Select an ECR image'
                            )
                        ]
                    )

                    echo "Selected image: ${selectedImage}"

                    env.SELECTED_IMAGE = selectedImage
                }
            }
        }

        stage('Start Container') {
            steps {
                dir('automation_with_python_exercises') {
                    withCredentials([
                        string(
                            credentialsId: 'ecr-credentials',
                            variable: 'ECR_PASSWORD'
                        )
                    ]) {
                        sh '''
                            /opt/jenkins-venv/bin/python deploy.py \
                                "$SELECTED_IMAGE" \
                                "$ECR_PASSWORD"
                        '''
                    }
                }
            }
        }

        stage('Validate Application') {
            steps {
                dir('automation_with_python_exercises') {
                    sh '''
                        /opt/jenkins-venv/bin/python validate.py "$SELECTED_IMAGE"
                    '''
                }
            }
        }
    }
}