#!/usr/bin/env
pipeline {
    agent any
    tools {
        nodejs 'node'
    }

    stages {
        stage('Increment app version') {
            steps {
             script {
                echo 'Incrementing app version'
                sh 'cd jenkins-exercises/app && npm version minor --no-git-tag-version'

                def packageJson = readJSON file: 'jenkins-exercises/app/package.json'
                def version = packageJson.version

                env.IMAGE_NAME = "${version}-${BUILD_NUMBER}"
             }
            }
        }
        stage('Test code') {
            steps {
                script {
                    echo 'Running test'
                    sh 'cd jenkins-exercises/app && npm install && npm run test'
                }
            }
        }
        stage('Build docker image') {
            steps {
                script {
                    echo 'Building docker image'
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                        sh "cd jenkins-exercises/app/ && docker build -t lihanda/demo-app:${IMAGE_NAME} ."
                        sh "echo $PASS | docker login -u $USER --password-stdin"
                        sh "docker push lihanda/demo-app:${IMAGE_NAME}"
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    echo 'Deploying the application ..'
                }
            }
        }
        stage('Commit version update') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'github-credentials', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                        sh 'git config --global user.email "jenkins@example.com"'
                        sh 'git config --global user.name "jenkins"'


                        sh 'git status'
                        sh 'git branch'
                        sh 'git config --list'

                        sh "git remote set-url origin https://${USER}:${PASS}@github.com/lihandafabius/Devops_Nana-Techworld_Bootcamp.git"
                        sh 'git add .'
                        sh 'git commit -m "ci: version bump"'
                        sh 'git push origin HEAD:main'
                    }
                }
            }
        }
    }

}