#!/usr/bin/env

@Library('Jenkins-shared-library')_

pipeline {
    agent any
    tools {
        nodejs 'node'
    }

    stages {
        stage('Check commit message') {
            steps {
                script {
                    commitCheck()
                }
            }
        }
        stage('Increment app version') {
            steps {
                script {
                    incrementAppVersion()
                }
            }
        }
        stage('Test code') {
            steps {
                script {
                    echo 'Running test'
                    sh 'cd jenkins-exercises/app && npm install && npm run test'
                }
            }
        }
        stage('Build docker image') {
            steps {
                script {
                    buildDockerImage 'lihanda/demo-app:${IMAGE_NAME}'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    echo 'Deploying the application ..'
                }
            }
        }
        stage('Commit version update') {
            steps {
                script {
                    commitVersionUpdate()
                }
            }
        }
    }

}