#!/usr/bin/env
pipeline {
    agent any
    tools {
        nodejs 'node'
    }

    stages {
        stage('Increment app version') {
            steps {
             script {
                echo 'Incrementing app version'
                sh 'cd jenkins-exercises/app && npm version minor --no-git-tag-version'

                def packageJson = readJSON file: 'jenkins-exercises/app/package.json'
                def version = packageJson.version

                env.IMAGE_NAME = "${version}-${BUILD_NUMBER}"
             }
            }
        }
        stage('Test code') {
            steps {
                script {
                    echo 'Running test'
                }
            }

        }
        stage('Commit version update') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'github-credentials', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                        sh 'git config --global user.email "jenkins@example.com"'
                        sh 'git config --global user.name "jenkins"'


                        sh 'git status'
                        sh 'git branch'
                        sh 'git config --list'

                        sh "git remote set-url origin https://${USER}:${PASS}@github.com/lihandafabius/Devops_Nana-Techworld_Bootcamp.git"
                        sh 'git add .'
                        sh 'git commit -m "ci: version bump"'
                        sh 'git push origin HEAD:main'
                    }
                }
            }
        }
    }

}