apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: mysql-java-app-ingress
spec:
  ingressClassName: nginx
  rules:
   - host: k8s-default-nginxing-53fdf512a8-be30515bec2a1dc2.elb.eu-north-1.amazonaws.com
     http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: java-mysql-app-service
              port:
                number: 8080