apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data: # if you use stringData, the values will be stored in plaintext, which is not secure. Use base64 encoded values instead.
  DB_PWD: bXlwYXNzd29yZA==
  DB_USER: bXl1c2Vy
