---
- name: Configure nginx web server
  hosts: webservers
  become: yes # execute tasks with elevated privileges
  tasks:
    - name: Uninstall nginx server
      apt:
        name: nginx=1.24.0-0ubuntu1
        state: absent
    
    - name: Start nginx service
      service:
        name: nginx
        state: stopped
        enabled: yes