---
- name: Install Docker
  hosts: docker_server
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        update_cache: yes
        state: present
    - name: Start Docker daemon
      systemd:
        name: docker
        state: started
        enabled: yes

- name: Install Docker Compose
  hosts: docker_server
  tasks:
    - name: Create Docker Compose directory
      file:
        path: ~/.docker/cli-plugins
        state: directory
    - name: Get architecture of remote host
      shell: uname -m
      register: architecture
    - name: Download Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{ architecture.stdout }}"
        dest: ~/.docker/cli-plugins/docker-compose
        mode: +x # Make the file executable

- name: Add ec2-user to docker group
  hosts: docker_server
  become: yes
  tasks:
    - name: Add ec2-user to docker group
      user: # allows to create a new user or modify an existing user
        name: ec2-user
        groups: docker
        append: yes 
    - name: Reconnect to apply group changes
      meta: reset_connection  

- name: Start docker containers
  hosts: docker_server
  vars_prompt:
    - name: docker_username
      prompt: "Enter your Docker Hub username"
      private: no
    - name: docker_password
      prompt: "Enter your Docker Hub password"
      private: yes
  tasks:
    - name: Copy docker-compose.yml to remote host
      copy:
        src: /home/fabius-lihanda/Devops/Devops_Nana-Techworld_Bootcamp/developing-with-docker/docker-compose.yaml
        dest: /home/ec2-user/docker-compose.yml
    - name: Docker login
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
    - name: Start Docker containers
      community.docker.docker_compose_v2:
        project_src: /home/ec2-user
        
