def gv
pipeline {
    agent any
    parameters {
        choice(name: 'VERSION', description: 'New version to deploy', choices: ['1.3.0', '1.4.0', '1.5.0'])
        booleanParam(name: 'RUN_TESTS', defaultValue: true, description: 'Whether to run tests')
    }

    stages {
        stage('init') {
            steps {
                script {
                    gv   = load 'jenkins/java-maven-app/script.groovy'
                }
            }
        }
        stage('Build') {
            steps {
                script{
                    gv.buildApp()
                }
            }
        }
        stage('Test') {
            when {
                expression {               
                    params.RUN_TESTS         
                }
            }
            steps {
                script{
                    gv.testApp()
                }
            }
        }
        stage('Deploy') {
            input{
                message "Select the environment to deploy to"
                ok "Done"
                parameters{
                    choice(name: 'ENV', description: 'Select environment to deploy', choices: ['dev', 'staging', 'prod'])
                }
            }
            steps {
                script{
                    gv.deployApp()
                    echo "Deploying to ${ENV}"
                }   
            }
        }
    }
}
