def gv
pipeline {
    agent any
    parameters {
        choice(name: 'VERSION', description: 'New version to deploy', choices: ['1.3.0', '1.4.0', '1.5.0'])
        booleanParam(name: 'RUN_TESTS', defaultValue: true, description: 'Whether to run tests')
    }

    stages {
        stage('init') {
            steps {
                script {
                    gv   = load 'script.groovy'
                }
            }
        }
        stage('Build') {
            steps {
                script{
                    gv.buildApp()
                }
            }
        }
        stage('Test') {
            when {
                expression {               
                    params.RUN_TESTS         
                }
            }
            steps {
                script{
                    gv.testApp()
                }
            }
        }
        stage('Deploy') {
            steps {
                script{
                    gv.deployApp()
                }   
            }
        }
    }
}
